Web/rawFlask/views/account.py
# coding=utf-8

from flask import Blueprint, render_template, jsonify, session, current_app, request, redirect, url_for, g
# from urllib import quote
import json
import traceback
from ..utils import ViewDecorate
from ..auth import Auth
from ..apps.UserApp import UserApp
import requests

__author__ = 'hanYong'

account = Blueprint('account', __name__)


class JSON_CODE(object):
    OK = 200
    PasswordError = 405
    Unauthorized = 401
    Forbidden = 403
    ServerError = 500
    RemoteError = 505


@account.route("/logout.json", methods=['GET'])
@ViewDecorate.record_call_exception()
def logout_raw():
    if session.get('user_token'):
        token = session.pop("user_token")
        um_id = session.pop("id")
        um = session.pop("um")
    return jsonify({'resCode': 200, 'data': 'ok'})


@account.route("/login.status.check.json", methods=['GET'])
@ViewDecorate.record_call_exception()
def login_status_check():
    if session.get('user_token') is not None:
        Auth.load_user()
        if g.user.get('permissions', list()).count('super.admin') > 0:
            g.user['isAdmin'] = True
        else:
            g.user['isAdmin'] = False
        return jsonify({'resCode': 200, 'data': g.user})
    else:
        return jsonify({'resCode': 404, 'data': {}})


@account.route("/users.list.json", methods=['GET'])
@ViewDecorate.record_call_exception()
def users_list():
    return jsonify({'resCode': 200, 'data': UserApp.users()})


@account.route("/login.json", methods=["POST"])
@ViewDecorate.record_call_exception()
def login_sso():
    user = request.get_json().get("user")
    um_id = None
    um = None
    data = None
    message = "successful"
    code = JSON_CODE.OK
    success = True
    appid = current_app.config.get("SSO_APP_ID")
    is_test_mode = current_app.config.get("IS_TEST")
    if current_app.debug:
        login_type = "local"
    else:
        login_type = "oa"
    try:
        req = requests.post("%s/%s" % (current_app.config.get("SSO_URL"), "account/api_login.json"), {
            "um": user["um"],
            "password": user["password"],
            "login_type": login_type,
            "is_debug": is_test_mode,
            "appid": appid
        })
        if req.status_code == 200:
            resp = req.json()
            code = resp["code"]
            if code == 200 and resp["success"]:
                session["user_token"] = resp["data"]
                url = '%s/account/user_info.json?token=%s&secret=%s&app=%d' % (
                    current_app.config.get('SSO_URL'),
                    session["user_token"],
                    current_app.config.get('SSO_APP_SECRET'),
                    current_app.config.get('SSO_APP_ID')
                )
                req = requests.get(url)
                resp = req.json()
                if resp['code'] == 200 and resp["success"]:
                    g.user = resp["data"]

                    if 'super.super' in g.user['permissions']:
                        session['is_super'] = 1
                    else:
                        session['is_super'] = 0

                    if 'login.login' in g.user['permissions'] or 'super.admin' in g.user['permissions']:
                        session['id'] = g.user['id']
                        session['um'] = g.user['um']
                        message = "successful"
                        current_app.logger.info('user login success ~> um %s token: %s' %
                                                (user['um'], session["user_token"]))
                        UserApp.login(user['um'], session["user_token"], JSON_CODE.OK)
                        if len(g.user.get('department', list())) > 0:
                            department = g.user['department'][0]
                        else:
                            department = ''
                        UserApp.sync_user(user['um'], g.user['name'], department)
                        code = JSON_CODE.OK
                        success = True
                        data = 0
                    else:
                        success = False
                        message = u'没有登录权限'
                        current_app.logger.info('user login fail ~> um %s token: %s message %s' %
                                                (user['um'], session["user_token"], u'没有登录权限'))
                        UserApp.login(user['um'], session["user_token"], JSON_CODE.Unauthorized)
                else:
                    current_app.logger.info('user login fail ~> um %s message %s' %
                                                    (user['um'], u'Passport出现未知错误'))
                    message = u"Passport出现未知错误"
                    UserApp.login(user['um'], '', JSON_CODE.RemoteError)
                    success = False
            else:
                current_app.logger.info('user login fail ~> um %s message %s' %
                                           (user['um'], resp["message"]))
                UserApp.login(user['um'], '', JSON_CODE.PasswordError)
                message = resp["message"]
                success = False
        else:
            current_app.logger.info('user login fail ~> um %s message %s' %
                                    (user['um'], u"验证失败，请检查密码是否正确"))
            UserApp.login(user['um'], '', JSON_CODE.PasswordError)
            message = u"验证失败，请检查密码是否正确"
            success = False
    except Exception as err:
        message = err.message
        success = False
        code = JSON_CODE.ServerError
        UserApp.login(user['um'], '', JSON_CODE.ServerError)
        current_app.logger.warning('user login fail internal error ~> %s' % traceback.format_exc()+'\n'+str(err))
    return jsonify({"code": code, "um_id": um_id, "um": um, "data": data, "message": message, "success": success})

Web/rawFlask/views/result.py
# -*- coding:utf8 -*-
from flask import Blueprint, render_template, jsonify, session, current_app, request

from flask_wtf import Form
from wtforms import StringField,SubmitField
from wtforms.validators import Required

from pymongo import *
import re

client = MongoClient()
db = client.BaiduYunPan           #数据库
db_shares = db.shares     #分享数据表单
db_followers = db.followers   #订阅表单
db_fans = db.fans         #粉丝表单
db_uids = db.uids

__auth__="Hugg"

result = Blueprint('Result',__name__)

class QueryForm(Form):
    query = StringField('query')
    submit = SubmitField('stb')

@result.route('/result.json',methods=['GET','POST'])
def query_result():
    rs = []
    form = QueryForm()
    query = form.query.data
    qw = re.split(" +",query.strip())

    for i in range(len(qw) - 1, -1, -1):
        qw.insert(i, r'.*')
    search = ''.join(qw)
    shares = db_shares.find({}, {'_id': 0, 'sharelist': 1})
    [rs.append(v) for s in shares for v in s.get('sharelist') if re.match(search, v.get('title'), flags=re.IGNORECASE)]

    return render_template("result.html", Query=query,
                                             ResultSet=rs)

Web/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>云盘搜索</title>

    <link rel="stylesheet" href="{{ url_for('static', filename="css/base2.css") }}" type="text/css">
</head>
<body>
    <div class="wrapper" id="wrap">
        <div class="header">
            <div class="top-nav">
                <ul>
                    <li><a onclick="st(this,'40030300','news')" href="http://news.sogou.com" uigs-id="nav_news" id="news">新闻</a></li>
                    <li class="cur"><span>网页</span></li>
                    <li><a onclick="st(this,'73141200','weixin')" href="http://weixin.sogou.com/" uigs-id="nav_weixin" id="weixinch">微信</a></li>
                    <li><a onclick="st(this,'40051200','zhihu')" href="http://zhihu.sogou.com/" uigs-id="nav_zhihu" id="zhihu">知乎</a></li>
                    <li><a onclick="st(this,'40030500','pic')" href="http://pic.sogou.com" uigs-id="nav_pic" id="pic">图片</a></li>
                    <li><a onclick="st(this,'40030600','video')" href="http://v.sogou.com/" uigs-id="nav_v" id="video">视频</a></li>
                    <li><a href="http://mingyi.sogou.com?fr=common_index_nav" uigs-id="nav_mingyi" id="mingyi" onclick="st(this,'','myingyi')">明医</a></li>
                    <li><a href="http://scholar.sogou.com?fr=common_index_nav" uigs-id="nav_scholar" id="scholar" onclick="st(this,'','scholar')">学术</a></li>
                    <li class="show-more">
                        <a href="javascript:void(0);" id="more-product" class="">更多<i class="m-arr"></i></a>
                        <div class="pos-more" id="products-box" style="display: none; top: 40px; opacity: 0;">
                            <span class="ico-san"></span>
                            <a onclick="st(this,'','overseas')" href="http://english.sogou.com?fr=common_index_nav" uigs-id="nav_overseas" id="overseas">英文</a>
                            <a onclick="st(this,'40031000')" href="http://map.sogou.com" uigs-id="nav_map" id="map">地图</a>
                            <a onclick="st(this,'web2ww')" href="http://wenwen.sogou.com/" uigs-id="nav_wenwen" id="index_more_wenwen">问问</a>
                            <a onclick="st(this,'40031500')" href="http://gouwu.sogou.com/" uigs-id="nav_gouwu" id="index_more_gouwu">购物</a>
                            <a onclick="st(this,'40051203')" href="http://baike.sogou.com/Home.v" uigs-id="nav_baike" id="index_more_baike">百科</a>
                            <a onclick="st(this)" href="http://zhishi.sogou.com" uigs-id="nav_zhishi" id="index_more_zhishi">知识</a>
                            <a onclick="st(this,'40050200')" href="http://mp3.sogou.com/" uigs-id="nav_music" id="index_more_music">音乐</a>
                            <a onclick="st(this,'40051205')" href="http://as.sogou.com/" uigs-id="nav_app" id="index_more_appli">应用</a>
                            <a onclick="st(this,'40051205','fanyi')" href="http://fanyi.sogou.com?fr=common_index_nav_pc" uigs-id="nav_fanyi" id="index_more_fanyi">翻译</a>
                            <a href="http://index.sogou.com" uigs-id="nav_index" id="index_more_index">指数</a>
                            <span class="all"><a onclick="st(this,'40051206')" href="http://www.sogou.com/docs/more.htm?v=1" uigs-id="nav_all" target="_blank">全部</a></span>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="user-box">
                <div class="local-weather" id="local-weather">
                    <div class="wea-box" id="cur-weather" style="display: block;">
                        <span class="c6">上海</span><i>
                        <img src="" width="16" height="16" title="多云" alt="多云">
                        </i>
                        <span class="c6">20°</span><span class="pj-w level2">良 64</span>
                    </div>
                </div>
                <span class="line" id="user-box-line" style=""></span>
                <div class="user-enter">
                    <a href="javascript:void(0);" id="show-card" style="" uigs-id="settings_show-card">显示卡片</a>
                    <a href="javascript:void(0);" uigs-id="settings_change-skin" id="changeSkinBtn">换肤</a>
                    <span class="s-dw">
                        <a href="javascript:void(0);" id="settings">设置</a>
                        <div class="pos-more" id="settings-box" style="display: none; top: 40px; opacity: 0;">
                            <span class="ico-san"></span>
                            <a href="javascript:void(0);" id="search-settings" uigs-id="settings_config">搜索设置</a>
                            <a href="javascript:void(0);" id="advanced-search" uigs-id="settings_advanced">高级搜索</a>
                            <a href="http://help.sogou.com/?w=01091500&amp;v=1" uigs-id="settings_help">帮助</a>
                        </div>
                    </span><a href="javascript:void(0);" class="enter" id="loginBtn">登录</a>            </div>
            </div>
        </div>
        <div class="content" id="content">
            <div class="pos-header" id="top-float-bar">
                <div class="part-one"></div>
                <div class="part-two" id="card-tab-layer">
                    <div class="c-top" id="top-card-tab"></div>
                </div>
            </div>
            <div class="logo2" id="logo-s"><span></span></div>
            <div class="logo" id="logo-l"><span></span></div>
            <div class="search-box" id="search-box">
                <form method="post" action="/qr/result.json" name="sf" id="sf" onsubmit="if(this.query.value=='')return false;document.sf._ast.value=Math.round(new Date().getTime()/1000);">
                    <span class="sec-input-box yuyin-cur">
                        <input type="text" placeholder="输入关键字" class="sec-input" name="query" id="query" maxlength="100" autocomplete="off" >
                    </span>
                    <span class="enter-input">
                        <input type="submit" value="so" id="stb" style="background:#477979;font-style: italic;border-bottom-right-radius: 20px;border-top-right-radius: 20px">
                    </span>
                    <!--
                    <input type="hidden" name="_asf" value="www.sogou.com">
                    <input type="hidden" name="_ast">
                    <input type="hidden" name="w" value="01019900">
                    <input type="hidden" name="p" value="40040100">
                    <input type="hidden" name="ie" value="utf8">
                    <input type="hidden" name="from" value="index-nologin">  -->
                </form>
            <a href="javascript:void(0);" uigs-id="voice_btn" id="voice-btn" class="fayin" title="语音搜索"></a></div>
        </div>
    </div>
    <script>
        var SugPara, uigs_para,
            msBrowserName = navigator.userAgent.toLowerCase(),
            msIsSe = false,
            msIsMSearch = false,
            queryinput = document.getElementById('query');

        uigs_para={
            "uigs_productid": "webapp",
            "type": "webindex_new",
            "stype": "nologin",
            "scrnwi": screen.width,
            "scrnhi": screen.height,
            "uigs_pbtag": "A",
            "uigs_cookie": "SUID,sct",
            "puid": "invaliduser",
            "cards": "",
            "cards_sw": "$cardEnabled",
            "skin": "$skinId",
            "skin_sw": "$skinEnable",
            "protocol": location.protocol.toLowerCase() == "https:" ? "https" : "http"
        };

        SugPara = {"enableSug":true,"sugType":"web","domain":"w.sugg.sogou.com","productId":"web","sugFormName":"sf","inputid":"query","submitId":"stb","suggestRid":"01015002","normalRid":"01019900","useParent":0 ,"sugglocation":"index","showVr":true,"showHotwords":true};


        function mk_con() {
            try {
                window.external.metasearch('make_connection', 'www.google.com.hk');
            } catch (e) {}
        }

        if (/se 2\.x/i.test(msBrowserName)) {
            msIsSe = true;
        }

        if (/metasr/i.test(msBrowserName)) {
            msIsMSearch = true;
        }

        if (queryinput) {
            if (msIsSe && msIsMSearch) {
                if (queryinput.addEventListener) {
                    queryinput.addEventListener('keypress', mk_con, false);
                    queryinput.addEventListener('keydown', mk_con, false)
                } else if (queryinput.attachEvent) {
                    queryinput.attachEvent('onkeypress', mk_con);
                    queryinput.attachEvent('onkeydown', mk_con);
                } else {
                    queryinput.onkeypress = mk_con;
                    queryinput.onkeydown = mk_con;
                }
            }
        }

        window.m_s_index = function() {
            var w = document.sf.query,
                c = Math.round((new Date().getTime() + Math.random()) * 1000);

            w.focus();

            if(new RegExp("kw=([^&]+)").test(location.search)) {
                if(w.value.length == 0) {
                    w.value = decodeURIComponent(RegExp.$1);
                }
            }

            if (document.cookie.indexOf("SUV=") < 0) {
                document.cookie = "SUV=" + c + ";path=/;expires=Sun, 29 July 2026 00:00:00 UTC;domain=sogou.com"
            }
        };

        function st(self, p, product, anchor) {
            var searchBox = document.sf.query,
                query = encodeURIComponent(searchBox.value),

                productUrl = {
                    "news": 'http://news.sogou.com/news?ie=utf8&query=',
                    "web": 'web?ie=utf8&query=',
                    "weixin": 'http://weixin.sogou.com/weixin?type=2&ie=utf8&query=',
                    "zhihu": 'http://zhihu.sogou.com/zhihu?ie=utf8&query=',
                    "pic": 'http://pic.sogou.com/pics?ie=utf8&query=',
                    "video": 'http://v.sogou.com/v?ie=utf8&query=',
                    "myingyi": 'http://mingyi.sogou.com/mingyi?ie=utf8&fr=common_index_nav&query=',
                    "overseas": 'http://english.sogou.com?b_o_e=1&ie=utf8&fr=common_index_nav&query=',
                    "scholar": 'http://scholar.sogou.com?ie=utf8&fr=common_index_nav&query=',
                    "fanyi": 'http://fanyi.sogou.com/?fr=common_index_nav_pc&ie=utf8&keyword='
                },
                newHref = productUrl[product] || self.href;

            function getConnectSymbol(url) {
                return url.indexOf("?") > -1 ? '&' : '?';
            }

            if(searchBox && searchBox.value !== ''){

                if(productUrl[product]) {
                    newHref = productUrl[product] + query;
                } else if(newHref.indexOf("kw=") > 0) {
                    newHref = newHref.replace(new RegExp("kw=[^&$]*"), "kw=" + query)
                } else {
                    newHref += getConnectSymbol(newHref) + 'kw=' + query;
                }
            }

            if(p){
                newHref += getConnectSymbol(newHref) + "p=" + p;
            }

            if (anchor && anchor.length > 0){
                newHref += "#" + anchor;
            }

            self.href = newHref;
        }

        window.cid = function(o, p) {
            var w = document.sf.query,
                q = encodeURIComponent(w.value);

            if (!q) {
                o.href += "?cid=" + p
            } else {
                if (p === "web2ww") {
                    o.href += "s/?cid=web2ww&w=" + q
                } else if (p === "web2bk") {
                    o.href += "SearchWeb.e?sp=S" + q + "&cid=web2bk"
                }
            }
        };

        window.m_s_index();
    </script>
</body>
</html>

Web/templates/index_tmp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0, maximum-scale=1, minimum-scale=1">
    <title>rawFlask 脚手架</title>
    <link href="{{ url_for('static', filename='bin/vendor/Roboto/roboto.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='bin/vendor/animateCss/animate.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='bin/js/style.css') }}" rel="stylesheet">
    <style></style>
</head>
<body style="margin: 0">
    <div id="systemVersionHidden" version="{{ version }}"></div>
    <div id="app" >
        <router-view name="header"></router-view>
        <router-view name="content"></router-view>
        <router-view name="footer"></router-view>
    </div>

    <script src="{{ url_for('static', filename='bin/js/vendor.bundle.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='bin/js/app.js') }}" type="text/javascript"></script>
</body>
</html>

Web/templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>云盘搜索</title>
</head>
<body>
    <h1> 查询"{{ Query }}"的结果： <br> </h1>
    <hr />
    <!-- 定义flask宏-->
    {% macro display_f(entry) %}
        <li>文件名:{{ entry['title'] }},  大小:{{ entry['size']/1000000 }}M,  链接：<a href="{{ entry['url'] }}">{{ entry['url'] }}</a></li>
    {% endmacro %}

    {% if ResultSet %}
    <ul>
        {% for rs in ResultSet %}
            <li>{{ display_f(rs) }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</body>
</html>

Web/templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>云盘搜索</title>

    <!--
    <link rel="stylesheet" href="/static/css/serial.css"  type="text/css">
    -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/serial.css') }}"  type="text/css">

</head>
<body class="gbody">
    <div class="gd">
        <div class="u1" >
            <ul>
                <li>热门资源 &nbsp</li>
                <li><a href="#video">视频</a></li>
                <li><a href="#file">文件</a></li>
                <li><a href="#music">音乐</a></li>
            </ul>
        </div>
        <div class="u2" >
            <ul>
                <li><a href="{{ url_for('account.login_status_check') }}">登录</a></li>
                <li><a href="#setup">设置</a> </li>
            </ul>
        </div>
    </div>
    <div class="frame-search">
        <form action="#" class="tb-search">
            <span>
                <input type="search" style="width:300px;height: 70px">
            </span>
            <span>
                <input type="submit" value="搜索" style="background-color: blue;color: white">
            </span>
        </form>
    </div>
</body>
</html>